global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']

  - job_name: 'stream_to_bronze'
    static_configs:
      - targets: ['stream_to_bronze:4040']  # Spark UI metrics, ajuste se usar endpoint Prometheus

  # Você pode adicionar mais targets para outras métricas
 
